set_property PACKAGE_PIN H16 [get_ports tmds_clk_p_0]
set_property PACKAGE_PIN D19 [get_ports {tmds_data_p_0[0]}]
set_property PACKAGE_PIN C20 [get_ports {tmds_data_p_0[1]}]
set_property PACKAGE_PIN B19 [get_ports {tmds_data_p_0[2]}]

create_clock -period 2.694 -name VIRTUAL_clk_5x_zynq_clk_wiz_0_1 -waveform {0.000 1.347}
set_output_delay -clock [get_clocks VIRTUAL_clk_5x_zynq_clk_wiz_0_1] -min -add_delay 0.000 [get_ports {tmds_data_n_0[*]}]
set_output_delay -clock [get_clocks VIRTUAL_clk_5x_zynq_clk_wiz_0_1] -max -add_delay 0.200 [get_ports {tmds_data_n_0[*]}]
set_output_delay -clock [get_clocks VIRTUAL_clk_5x_zynq_clk_wiz_0_1] -min -add_delay 0.000 [get_ports {tmds_data_p_0[*]}]
set_output_delay -clock [get_clocks VIRTUAL_clk_5x_zynq_clk_wiz_0_1] -max -add_delay 0.200 [get_ports {tmds_data_p_0[*]}]
set_output_delay -clock [get_clocks VIRTUAL_clk_5x_zynq_clk_wiz_0_1] -min -add_delay 0.000 [get_ports tmds_clk_n_0]
set_output_delay -clock [get_clocks VIRTUAL_clk_5x_zynq_clk_wiz_0_1] -max -add_delay 0.200 [get_ports tmds_clk_n_0]
set_output_delay -clock [get_clocks VIRTUAL_clk_5x_zynq_clk_wiz_0_1] -min -add_delay 0.000 [get_ports tmds_clk_p_0]
set_output_delay -clock [get_clocks VIRTUAL_clk_5x_zynq_clk_wiz_0_1] -max -add_delay 0.200 [get_ports tmds_clk_p_0]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_pwdn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_rstn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_pclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data_0[0]}]
set_property PACKAGE_PIN Y14 [get_ports {cmos_pwdn[0]}]
set_property PACKAGE_PIN V17 [get_ports {cmos_rstn[0]}]
set_property PACKAGE_PIN U14 [get_ports cmos_pclk_0]
set_property PACKAGE_PIN N17 [get_ports {cmos_data_0[7]}]
set_property PACKAGE_PIN U19 [get_ports {cmos_data_0[6]}]
set_property PACKAGE_PIN W19 [get_ports {cmos_data_0[5]}]
set_property PACKAGE_PIN W18 [get_ports {cmos_data_0[4]}]
set_property PACKAGE_PIN Y19 [get_ports {cmos_data_0[3]}]
set_property PACKAGE_PIN V18 [get_ports {cmos_data_0[2]}]
set_property PACKAGE_PIN Y18 [get_ports {cmos_data_0[1]}]
set_property PACKAGE_PIN U17 [get_ports {cmos_data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_herf_0]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_vsync_0]
set_property PACKAGE_PIN V15 [get_ports cmos_herf_0]
set_property PACKAGE_PIN P15 [get_ports cmos_vsync_0]


set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN U15 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN W15 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN Y14 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN V17 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN V20 [get_ports {GPIO_0_0_tri_io[4]}]
