# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/DESKTOP/code/IMG/IMG.srcs/sources_1/bd/zynq/ip/zynq_v_vid_in_axi4s_0_0/zynq_v_vid_in_axi4s_0_0.xci
# IP: The module: 'zynq_v_vid_in_axi4s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DESKTOP/code/IMG/IMG.srcs/sources_1/bd/zynq/ip/zynq_v_vid_in_axi4s_0_0/zynq_v_vid_in_axi4s_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/DESKTOP/code/IMG/IMG.srcs/sources_1/bd/zynq/ip/zynq_v_vid_in_axi4s_0_0/zynq_v_vid_in_axi4s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/DESKTOP/code/IMG/IMG.srcs/sources_1/bd/zynq/ip/zynq_v_vid_in_axi4s_0_0/zynq_v_vid_in_axi4s_0_0.xci
# IP: The module: 'zynq_v_vid_in_axi4s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DESKTOP/code/IMG/IMG.srcs/sources_1/bd/zynq/ip/zynq_v_vid_in_axi4s_0_0/zynq_v_vid_in_axi4s_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/DESKTOP/code/IMG/IMG.srcs/sources_1/bd/zynq/ip/zynq_v_vid_in_axi4s_0_0/zynq_v_vid_in_axi4s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
