# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/img.xdc

# Block Designs: bd/zynq/zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_vdma_0_0/zynq_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_vdma_0_0 || ORIG_REF_NAME==zynq_axi_vdma_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_v_tc_0_0/zynq_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_v_tc_0_0 || ORIG_REF_NAME==zynq_v_tc_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_v_axi4s_vid_out_0_0/zynq_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zynq_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_smc_0/zynq_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_smc_0 || ORIG_REF_NAME==zynq_axi_smc_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_rst_ps7_0_100M_0/zynq_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xbar_0/zynq_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_xbar_0 || ORIG_REF_NAME==zynq_xbar_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps7_0_axi_periph_0/zynq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_vga2hdmi_0_1/zynq_vga2hdmi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_vga2hdmi_0_1 || ORIG_REF_NAME==zynq_vga2hdmi_0_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_clk_wiz_0_1/zynq_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_clk_wiz_0_1 || ORIG_REF_NAME==zynq_clk_wiz_0_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_util_vector_logic_0_0/zynq_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_util_vector_logic_0_0 || ORIG_REF_NAME==zynq_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_cmos_capture_0_0/zynq_cmos_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_cmos_capture_0_0 || ORIG_REF_NAME==zynq_cmos_capture_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_v_vid_in_axi4s_0_0/zynq_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==zynq_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_auto_pc_0 || ORIG_REF_NAME==zynq_auto_pc_0} -quiet] -quiet

# XDC: bd/zynq/zynq_ooc.xdc
