set_property SRC_FILE_INFO {cfile:C:/Users/maccura/Desktop/DIP/IMG/IMG.srcs/constrs_1/new/img.xdc rfile:../../../IMG.srcs/constrs_1/new/img.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports tmds_clk_p_0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {tmds_data_p_0[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {tmds_data_p_0[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {tmds_data_p_0[2]}]
